#!/usr/bin/python

import sys, argparse, errno, os, shutil, subprocess

supported = ['ext4', 'xfs', 'btrfs', 'f2fs', 'gfs2', 'hfsplus', 'reiserfs', 'fat']

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('-t', dest='type')
  parser.add_argument('-c', action='store_true')
  # parser.add_argument('-o', dest='object')
  
  args = parser.parse_args()

  if args.type is None or args.type not in supported:
    print 'Please set valid type'
    sys.exit(1)

  # if args.object is None or args.object not in ['fsfuzz', 'executor']:
  #   print 'Please set valid object'
  #   sys.exit(1)

  if args.c:
    subprocess.check_call('make clean', shell=True)
    subprocess.check_call('make -C tools/lkl clean', shell=True)
  
  # copy config
  subprocess.call('cp -f %s-config arch/lkl/defconfig' % args.type, shell=True)
  
  # compile with instrumenting gcc
  dir_path = os.path.dirname(os.path.realpath(__file__))
  subprocess.call('make -C tools/lkl -j CC="%s/../ff-gcc/ff-gcc fs/%s"' % (dir_path, args.type), shell=True)

  # copy object file
  subprocess.call('cp -f tools/lkl/fsfuzz tools/lkl/%s-fsfuzz' % args.type, shell=True)
  subprocess.call('cp -f tools/lkl/executor tools/lkl/%s-executor' % args.type, shell=True)
  subprocess.call('cp -f tools/lkl/combined tools/lkl/%s-combined' % args.type, shell=True)
